[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_SITE_URL = "https://cheshraidtoearn.netlify.app"

[[redirects]]
  from = "/auth/callback"
  to = "/"
  status = 200
  force = true
